### PR TITLE
feat: Introduce automatic LRO polling, integrate latest compute API definitions

### PR DESCRIPTION
**Pull request by Neenu1995**
feat: Introduce automatic LRO polling; all LRO methods now return `OperationFuture<>` instead of `Operation` and poling is done automatically; calling `cancel()` on the future will cancel polling but not the operation itself on the server side.
chore: migrate to owlbot
fix: rename `IPProtocol` to `IPProtocolEnum`

### CODE REVIEW

**Comment by vam-google** [comment]
@georgiyekkert PTAL. Please update Integration Test according to the changes.

The expected changes:
1) Strings must be used instead of enums
2) LRO methos are now in place (what used to return Operation now returns `OpratoinFuture<Operation, Operation>`)

**Review by eaball35 — APPROVED** [review]

**Comment by Neenu1995** [comment]
Hi @georgiyekkert,
The integration tests are failing. Would you mind taking a look?

**Comment by georgiyekkert** [comment]
Looking

**Comment by georgiyekkert** [comment]
I was able to reproduce the issue locally, an image insert fails with:

  errors:
  - code: RESOURCE_OPERATION_RATE_EXCEEDED
    message: Operation rate exceeded for resource 'projects/debian-cloud/global/images/debian-10-buster-v20210721'.
      Too frequent operations from the source resource.

I'm going to try to fix or skip this test. The error doesn't look related to library changes.

**Comment by georgiyekkert** [comment]
confirmed: it's not a library issue, the API has a limitation - you can create only 6 images per hour per project. I'll update test in a separate PR.

**Review by vam-google — APPROVED** [review]
LGTM

**Pull request merged**
