### PR TITLE
feat!: add includeAllScopes to aggregatedList* methods

### PR DESCRIPTION
**Pull request by vam-google**
This PR depends on newer version of synttool: https://github.com/googleapis/synthtool/pull/459

### CODE REVIEW

**Comment by vam-google** [comment]
@chingor13 PTAL

**Comment by vam-google** [comment]
@hzyi-google PTAL. Looks like resoruce names are broken for discogapic

**Comment by hzyi-google** [comment]
@vam-google this seems to be why it failed: https://github.com/googleapis/java-compute/pull/94/files#diff-976abdd66f137213124fe3ee8fc82efcR184

It's probably due to a breaking change in discovery doc.

**Comment by vam-google** [comment]
Thanks Hanzhen!

@hzyi-google @chingor13 Since this is an alpha library I believe making breaking changes should be totally acceptable, WDYT?

**Comment by hzyi-google** [comment]
I'm fine with breaking changes.

**Pull request merged**
